<a href="https://colab.research.google.com/github/shemi024/data-preprocessing/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array(([1,2,3],[4,5,6]))
b=np.array(([4,5,6],[7,8,9]))
print("sum is:",a+b)
print("substraction is:",a - b)
print("multiplicatin is:",a*b)
print("division is:",a/b)
print("type is",type(a))
print("respaed is:",a.reshape(2,3))

print("transpose of array is:",a.transpose())
print("mean of array is:",a.mean())
print("std is\n:",a.std())
print("the variable is :",a.var())
print("copay is :",a.copy())
print("minimun value:",a.min())
print("maximum value:",a.max())
print("max argument value is:",a.argmax())
print("min argument value is:",a.argmin())
print("mean of row is :",a.mean(axis=0))
print("mean of column is :",a.mean(axis=1))
print("dimension od array",a.ndim)
print("coverted in to :",a.tostring)
print("from string is :",np.fromstring(a))
print("the array is filled with zero:",a.fill(0))


sum is: [[ 5  7  9]
 [11 13 15]]
substraction is: [[-3 -3 -3]
 [-3 -3 -3]]
multiplicatin is: [[ 4 10 18]
 [28 40 54]]
division is: [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
type is <class 'numpy.ndarray'>
respaed is: [[1 2 3]
 [4 5 6]]
transpose of array is: [[1 4]
 [2 5]
 [3 6]]
mean of array is: 3.5
std is
: 1.707825127659933
the variable is : 2.9166666666666665
copay is : [[1 2 3]
 [4 5 6]]
minimun value: 1
maximum value: 6
max argument value is: 5
min argument value is: 0
mean of row is : [2.5 3.5 4.5]
mean of column is : [2. 5.]
dimension od array 2
coverted in to : <built-in method tostring of numpy.ndarray object at 0x7f5f25d99620>
from string is : [4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]
the array is filled with zero: None


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead


In [ ]:
c=np.array([1,2,3])
print(c)
c.fill(1)
print(c)

[1 2 3]
[1 1 1]
